import { AlertType } from "@/services/alert/interface";
import { defineStore } from "pinia";

export const internationalDownloadAnomalyData: AlertType[] = [
  {
    eventId: "INT_DOWNLOAD_001",
    eventType: 4,
    attackerAsn: 0,
    victimAsn: 0,
    leakByAsn: 0,
    leakToAsnList: [],
    conspiratorList: [],
    outageAsn: null,
    isTransitAs: 0,
    affectedPrefixNum: 15,
    desc: "微生物所科研用户遭遇下载失败，访问DDBJ受阻",
    prefix: "",
    isImportantService: 1,
    startTime: "2024-01-15T10:30:00Z",
    endTime: "",
    eventStartTime: "2024-01-15T10:30:00Z",
    eventEndTime: "",
    outageAs: {
      asn: 174,
      asnName: "COGENT-174",
      countryIso: "JP",
      countryName: "Japan",
      latitude: 40.7128,
      longitude: -74.006,
      organizationOrgId: "ORG-CH1-ARIN",
      organizationOrgName: "Cogent Communications",
      rank: 15,
    },
    InternationalExtra: {
      probePoint: "微生物所",
      probeIp: "202.108.22.5",
      dataSource: "DDBJ",
      dataCenter: "DDBJ-Japan-Tokyo",
      dataSourceUrl: "https://ftp.ddbj.nig.ac.jp/",
      tool: "curl",
      status: "failed",
      responseTime: 8500,
      connectTime: 5200,
      dnsResolveTime: 890,
      sslHandshakeTime: 2410,
      downloadSpeed: 0,
      uploadSpeed: 0,
      packetLoss: 15.2,
      jitter: 8.5,
      bandwidth: 12.3,
      throughput: 0,
      targetCountry: "日本",
      targetRegion: "东京",
      distance: 2100,
      hopCount: 12,
      networkPath: "北京→东京",
      isp: "中国电信",
      timestamp: "2025-01-14 15:30:00",
      successToolCount: 1,
      totalToolCount: 3,
      bestResponseTime: 312,
      overallStatus: "failed",
      errorMessage: "Connection timeout to DDBJ FTP server",
      errorCode: 504,
      // 同一探测点到所有数据源的探测结果
      sameProbeToAllSources: [
        {
          dataSource: "NCBI",
          tool: "curl",
          status: "success",
          responseTime: 189,
          connectTime: 95,
          dnsResolveTime: 28,
          sslHandshakeTime: 67,
          downloadSpeed: 48.7,
          uploadSpeed: 14.1,
          packetLoss: 0.0,
          jitter: 1.8,
          bandwidth: 72.3,
          throughput: 6.02,
        },
        {
          dataSource: "EMBL-EBI",
          tool: "curl",
          status: "success",
          responseTime: 125,
          connectTime: 65,
          dnsResolveTime: 18,
          sslHandshakeTime: 42,
          downloadSpeed: 58.3,
          uploadSpeed: 16.7,
          packetLoss: 0.0,
          jitter: 1.3,
          bandwidth: 81.2,
          throughput: 7.45,
        },
        {
          dataSource: "DDBJ",
          tool: "curl",
          status: "failed",
          responseTime: 8500,
          connectTime: 5200,
          dnsResolveTime: 890,
          sslHandshakeTime: 2410,
          downloadSpeed: 0,
          uploadSpeed: 0,
          packetLoss: 15.2,
          jitter: 8.5,
          bandwidth: 12.3,
          throughput: 0,
          errorCode: 504,
          errorMessage: "Connection timeout to DDBJ FTP server",
        },
      ],
      // 所有探测点到同一数据源的探测结果
      allProbesToSameSource: [
        {
          probePoint: "微生物所",
          probeIp: "202.108.22.5",
          tool: "curl",
          status: "failed",
          responseTime: 8500,
          connectTime: 5200,
          dnsResolveTime: 890,
          sslHandshakeTime: 2410,
          downloadSpeed: 0,
          uploadSpeed: 0,
          packetLoss: 15.2,
          jitter: 8.5,
          bandwidth: 12.3,
          throughput: 0,
          errorCode: 504,
          errorMessage: "Connection timeout to DDBJ FTP server",
        },
        {
          probePoint: "国家生物信息中心",
          probeIp: "124.16.164.109",
          tool: "curl",
          status: "success",
          responseTime: 145,
          connectTime: 75,
          dnsResolveTime: 22,
          sslHandshakeTime: 48,
          downloadSpeed: 55.6,
          uploadSpeed: 16.2,
          packetLoss: 0.0,
          jitter: 1.2,
          bandwidth: 79.5,
          throughput: 6.98,
        },
        {
          probePoint: "武汉病毒所",
          probeIp: "202.96.209.5",
          tool: "curl",
          status: "success",
          responseTime: 160,
          connectTime: 82,
          dnsResolveTime: 25,
          sslHandshakeTime: 53,
          downloadSpeed: 52.3,
          uploadSpeed: 15.1,
          packetLoss: 0.0,
          jitter: 1.5,
          bandwidth: 75.8,
          throughput: 6.45,
        },
      ],
    },
  },
  {
    eventId: "INT_DOWNLOAD_002",
    eventType: 5,
    attackerAsn: 0,
    victimAsn: 0,
    leakByAsn: 0,
    leakToAsnList: [],
    conspiratorList: [],
    outageAsn: null,
    isTransitAs: 0,
    affectedPrefixNum: 8,
    prefix: "",
    isImportantService: 0,
    startTime: "2024-01-16T14:20:00Z",
    endTime: "2024-01-16T15:30:00Z",
    eventStartTime: "2024-01-16T14:20:00Z",
    eventEndTime: "2024-01-16T14:20:45Z",
    desc: "武汉病毒所科研用户访问EBI受阻",
    outageAs: {
      asn: 6453,
      asnName: "HURRICANE",
      countryIso: "US",
      countryName: "United States",
      latitude: 37.7749,
      longitude: -122.4194,
      organizationOrgId: "ORG-HT2-ARIN",
      organizationOrgName: "Hurricane Electric LLC",
      rank: 8,
    },
    InternationalExtra: {
      probePoint: "武汉病毒所",
      probeIp: "202.96.209.5",
      dataSource: "EMBL-EBI",
      dataCenter: "EMBL-UK-Cambridge",
      dataSourceUrl: "https://ftp.ebi.ac.uk/",
      tool: "curl",
      status: "timeout",
      responseTime: 12000,
      connectTime: 0,
      dnsResolveTime: 0,
      sslHandshakeTime: 0,
      downloadSpeed: 0,
      uploadSpeed: 0,
      packetLoss: 25.8,
      jitter: 12.3,
      bandwidth: 8.7,
      throughput: 0,
      targetCountry: "英国",
      targetRegion: "剑桥",
      distance: 9214,
      hopCount: 25,
      networkPath: "上海→香港→伦敦",
      isp: "中国联通",
      timestamp: "2025-01-14 15:30:00",
      successToolCount: 2,
      totalToolCount: 3,
      bestResponseTime: 189,
      overallStatus: "failed",
      errorMessage: "Request timeout to EMBL-EBI FTP server",
      errorCode: 408,
      // 同一探测点到所有数据源的探测结果
      sameProbeToAllSources: [
        {
          dataSource: "NCBI",
          tool: "curl",
          status: "success",
          responseTime: 195,
          connectTime: 98,
          dnsResolveTime: 26,
          sslHandshakeTime: 71,
          downloadSpeed: 49.5,
          uploadSpeed: 14.3,
          packetLoss: 0.0,
          jitter: 1.7,
          bandwidth: 71.8,
          throughput: 6.21,
        },
        {
          dataSource: "EMBL-EBI",
          tool: "curl",
          status: "timeout",
          responseTime: 12000,
          connectTime: 0,
          dnsResolveTime: 0,
          sslHandshakeTime: 0,
          downloadSpeed: 0,
          uploadSpeed: 0,
          packetLoss: 25.8,
          jitter: 12.3,
          bandwidth: 8.7,
          throughput: 0,
          errorCode: 408,
          errorMessage: "Request timeout to EMBL-EBI FTP server",
        },
        {
          dataSource: "DDBJ",
          tool: "curl",
          status: "success",
          responseTime: 160,
          connectTime: 82,
          dnsResolveTime: 25,
          sslHandshakeTime: 55,
          downloadSpeed: 52.1,
          uploadSpeed: 15.2,
          packetLoss: 0.0,
          jitter: 1.4,
          bandwidth: 76.5,
          throughput: 6.58,
        },
      ],
      // 所有探测点到同一数据源的探测结果
      allProbesToSameSource: [
        {
          probePoint: "武汉病毒所",
          probeIp: "202.96.209.5",
          tool: "curl",
          status: "timeout",
          responseTime: 12000,
          connectTime: 0,
          dnsResolveTime: 0,
          sslHandshakeTime: 0,
          downloadSpeed: 0,
          uploadSpeed: 0,
          packetLoss: 25.8,
          jitter: 12.3,
          bandwidth: 8.7,
          throughput: 0,
          errorCode: 408,
          errorMessage: "Request timeout to EMBL-EBI FTP server",
        },
        {
          probePoint: "国家生物信息中心",
          probeIp: "124.16.164.109",
          tool: "curl",
          status: "success",
          responseTime: 125,
          connectTime: 65,
          dnsResolveTime: 18,
          sslHandshakeTime: 42,
          downloadSpeed: 58.3,
          uploadSpeed: 16.7,
          packetLoss: 0.0,
          jitter: 1.3,
          bandwidth: 81.2,
          throughput: 7.45,
        },
        {
          probePoint: "微生物所",
          probeIp: "202.108.22.5",
          tool: "curl",
          status: "success",
          responseTime: 138,
          connectTime: 70,
          dnsResolveTime: 20,
          sslHandshakeTime: 48,
          downloadSpeed: 55.8,
          uploadSpeed: 15.9,
          packetLoss: 0.0,
          jitter: 1.5,
          bandwidth: 78.6,
          throughput: 7.02,
        },
      ],
    },
  },
  {
    eventId: "INT_DOWNLOAD_003",
    eventType: 6,
    attackerAsn: 0,
    victimAsn: 0,
    leakByAsn: 0,
    leakToAsnList: [],
    conspiratorList: [],
    outageAsn: undefined,
    isTransitAs: 0,
    affectedPrefixNum: 12,
    prefix: "",
    isImportantService: 1,
    startTime: "2024-01-17T09:15:00Z",
    endTime: "2024-01-17T11:20:00Z",
    eventStartTime: "2024-01-17T09:15:00Z",
    eventEndTime: "2024-01-17T09:15:30Z",
    desc: "国家生物信息中心科研用户访问NCBI受阻",
    outageAs: {
      asn: 1299,
      asnName: "TELIANET",
      countryIso: "US",
      countryName: "United States",
      latitude: 38.8951,
      longitude: -77.0364,
      organizationOrgId: "ORG-TS1-RIPE",
      organizationOrgName: "Telia Company AB",
      rank: 12,
    },
    InternationalExtra: {
      probePoint: "国家生物信息中心",
      probeIp: "124.16.164.109",
      dataSource: "NCBI",
      dataCenter: "NCBI-US-East",
      dataSourceUrl: "https://ftp.ncbi.nlm.nih.gov/",
      tool: "curl",
      status: "failed",
      responseTime: 1850,
      connectTime: 320,
      dnsResolveTime: 45,
      sslHandshakeTime: 185,
      downloadSpeed: 0,
      uploadSpeed: 0,
      packetLoss: 0.0,
      jitter: 2.1,
      bandwidth: 85.6,
      throughput: 0,
      targetCountry: "美国",
      targetRegion: "马里兰州",
      distance: 11987,
      hopCount: 19,
      networkPath: "北京→香港→洛杉矶",
      isp: "中国科技网",
      timestamp: "2025-01-17 09:20:00",
      successToolCount: 0,
      totalToolCount: 3,
      bestResponseTime: 0,
      overallStatus: "failed",
      errorMessage: "HTTP 403 Forbidden - Access denied",
      errorCode: 403,
      // 同一探测点到所有数据源的探测结果
      sameProbeToAllSources: [
        {
          dataSource: "NCBI",
          tool: "curl",
          status: "failed",
          responseTime: 1850,
          connectTime: 320,
          dnsResolveTime: 45,
          sslHandshakeTime: 185,
          downloadSpeed: 0,
          uploadSpeed: 0,
          packetLoss: 0.0,
          jitter: 2.1,
          bandwidth: 85.6,
          throughput: 0,
          errorCode: 403,
          errorMessage: "HTTP 403 Forbidden - Access denied",
        },
        {
          dataSource: "EMBL-EBI",
          tool: "curl",
          status: "success",
          responseTime: 125,
          connectTime: 65,
          dnsResolveTime: 18,
          sslHandshakeTime: 42,
          downloadSpeed: 58.3,
          uploadSpeed: 16.7,
          packetLoss: 0.0,
          jitter: 1.3,
          bandwidth: 81.2,
          throughput: 7.45,
        },
        {
          dataSource: "DDBJ",
          tool: "curl",
          status: "success",
          responseTime: 145,
          connectTime: 75,
          dnsResolveTime: 22,
          sslHandshakeTime: 48,
          downloadSpeed: 55.6,
          uploadSpeed: 16.2,
          packetLoss: 0.0,
          jitter: 1.2,
          bandwidth: 79.5,
          throughput: 6.98,
        },
      ],
      // 所有探测点到同一数据源的探测结果
      allProbesToSameSource: [
        {
          probePoint: "国家生物信息中心",
          probeIp: "124.16.164.109",
          tool: "curl",
          status: "failed",
          responseTime: 1850,
          connectTime: 320,
          dnsResolveTime: 45,
          sslHandshakeTime: 185,
          downloadSpeed: 0,
          uploadSpeed: 0,
          packetLoss: 0.0,
          jitter: 2.1,
          bandwidth: 85.6,
          throughput: 0,
          errorCode: 403,
          errorMessage: "HTTP 403 Forbidden - Access denied",
        },
        {
          probePoint: "微生物所",
          probeIp: "202.108.22.5",
          tool: "curl",
          status: "success",
          responseTime: 189,
          connectTime: 95,
          dnsResolveTime: 28,
          sslHandshakeTime: 67,
          downloadSpeed: 48.7,
          uploadSpeed: 14.1,
          packetLoss: 0.0,
          jitter: 1.8,
          bandwidth: 72.3,
          throughput: 6.02,
        },
        {
          probePoint: "武汉病毒所",
          probeIp: "202.96.209.5",
          tool: "curl",
          status: "success",
          responseTime: 195,
          connectTime: 98,
          dnsResolveTime: 26,
          sslHandshakeTime: 71,
          downloadSpeed: 49.5,
          uploadSpeed: 14.3,
          packetLoss: 0.0,
          jitter: 1.7,
          bandwidth: 71.8,
          throughput: 6.21,
        },
      ],
    },
  },
];

const newAlert: AlertType = {
  eventId: "INT_DOWNLOAD_003",
  eventType: 4,
  attackerAsn: 0,
  victimAsn: 0,
  leakByAsn: 0,
  leakToAsnList: [],
  conspiratorList: [],
  outageAsn: null,
  isTransitAs: 0,
  affectedPrefixNum: 12,
  prefix: "124.16.164.0/24",
  isImportantService: 1,
  startTime: "2024-01-17T09:15:00Z",
  endTime: "2024-01-17T11:20:00Z",
  eventStartTime: "2024-01-17T09:15:00Z",
  eventEndTime: "2024-01-17T11:20:00Z",
  desc: "国家生物信息中心科研用户访问NCBI受阻",
  outageAs: {
    asn: 1299,
    asnName: "TELIANET",
    countryIso: "SE",
    countryName: "Sweden",
    latitude: 59.3293,
    longitude: 18.0686,
    organizationOrgId: "ORG-TS1-RIPE",
    organizationOrgName: "Telia Company AB",
    rank: 12,
  },
  InternationalExtra: {
    probePoint: "国家生物信息中心",
    probeIp: "124.16.164.109",
    dataSource: "NCBI",
    dataCenter: "NCBI-US-East",
    dataSourceUrl: "https://ftp.ncbi.nlm.nih.gov/",
    tool: "curl",
    status: "failed",
    responseTime: 6500,
    connectTime: 4200,
    dnsResolveTime: 750,
    sslHandshakeTime: 1550,
    downloadSpeed: 0,
    uploadSpeed: 0,
    packetLoss: 8.7,
    jitter: 5.2,
    bandwidth: 35.6,
    throughput: 0,
    targetCountry: "美国",
    targetRegion: "马里兰州",
    distance: 11987,
    hopCount: 19,
    networkPath: "北京→香港→洛杉矶",
    isp: "中国科技网",
    timestamp: "2025-01-14 15:30:00",
    successToolCount: 2,
    totalToolCount: 3,
    bestResponseTime: 145,
    overallStatus: "failed",
    errorMessage: "HTTP 403 Forbidden - Access denied",
    errorCode: 403,
  },
};

export const useAlertList = defineStore("alert", {
  state: () => {
    return {
      list: internationalDownloadAnomalyData,
    };
  },
  actions: {
    addAlert(info: { desc: string; time: number }) {
      // newAlert.
      //  desc: `国家生物信息中心科研用户遭遇${type}，访问NCBI受阻`,
      // time: new Date().valueOf(),
      // 通过这两个信息把 newAlert 补充完整后加入列表
      newAlert.eventId = "INT_DOWNLOAD_003" + Math.random().toString(36).substring(2, 8);
      newAlert.desc = info.desc;
      newAlert.startTime = new Date(info.time).toString();
      newAlert.endTime = new Date(info.time).toString();
      newAlert.eventStartTime = new Date(info.time).toString();
      newAlert.eventEndTime = new Date(info.time).toString();

      this.list.push(newAlert);
    },
  },
});
