server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/frontend;

        index index.html index.htm;
        server_name _;

        location /cloudflare {
            rewrite ^/cloudflare(/.*)$ $1 break;
            proxy_pass https://api.cloudflare.com;
            proxy_set_header x-forwarded-for $remote_addr;
        }

        location /api {
            rewrite ^/api(/.*)$ $1 break;
            proxy_pass http://127.0.0.1:9201;
            proxy_set_header x-forwarded-for $remote_addr;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
}
